stages:
  - test

# GCC 8, C++98, Release
linux_x86_64_gcc8_cxx98_release:
  tags:
    - linux
  variables:
    CI_DEBUG_TRACE: "true" #print env variables
  stage: test
  image: gcc:8
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="linux_x86_64_gcc8_cxx98_release" -D CTEST_SITE="[gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/gcc -D CXXNAME=/usr/local/bin/g++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=98;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    
# GCC 9, C++11, Release
linux_x86_64_gcc9_cxx11_release:
  tags:
    - linux
  stage: test
  image: gcc:9
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="linux_x86_64_gcc9_cxx11_release" -D CTEST_SITE="[gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/gcc -D CXXNAME=/usr/local/bin/g++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=11;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests

# GCC 10, C++14, Release
linux_x86_64_gcc10_cxx14_release:
  tags:
    - linux
  stage: test
  image: gcc:10
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="linux_x86_64_gcc10_cxx14_release" -D CTEST_SITE="[gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/gcc -D CXXNAME=/usr/local/bin/g++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=14;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests

# Clang 7, C++98, Release
linux_x86_64_clang7_cxx98_release:
  tags:
    - linux
  stage: test
  image: silkeh/clang:7
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="linux_x86_64_clang7_cxx98_release" -D CTEST_SITE="[gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=98;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    
# Clang 8, C++11, Release
linux_x86_64_clang8_cxx11_release:
  tags:
    - linux
  stage: test
  image: silkeh/clang:8
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="linux_x86_64_clang8_cxx11_release" -D CTEST_SITE="[gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=11;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests

# Clang 9, C++14, Release
linux_x86_64_clang9_cxx14_release:
  tags:
    - linux
  stage: test
  image: silkeh/clang:9
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="linux_x86_64_clang9_cxx14_release" -D CTEST_SITE="[gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=14;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests

# Clang 10, C++17, Release
linux_x86_64_clang10_cxx17_release:
  tags:
    - linux
  stage: test
  image: silkeh/clang:10
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="linux_x86_64_clang10_cxx17_release" -D CTEST_SITE="[gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=17;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests

# Clang 11, C++20, Release
linux_x86_64_clang11_cxx20_release:
  tags:
    - linux
  stage: test
  image: silkeh/clang:11
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="linux_x86_64_clang11_cxx20_release" -D CTEST_SITE="[gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=20;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
