################################################################################
# GitLab CI is used for multiple purposes
#
# 1. Building and testing of commits to all branches except 'ci_test' and 
#   'coverity_scan' and sending of the ctest results to the CDASH server
#    - these jobs exclude external pull requests and the two branches 
#      'ci_test' and 'coverity_scan' by the rule
#       except:
#       - external_pull_requests
#       - ci_test
#       - coverity_scan
#
# 2. Building and testing of external pull requests (PRs) [to be added]
#
# 3. Building and extensive testing of commits to branch 'ci_test' [to be added]
#
# 4. Coverity scan of commits to branch 'coverity_scan' [to be added]
################################################################################

stages:
  - test
  
################################################################################
# 1. Building and testing of commits to all branches except 'ci_test' and 
#    'coverity_scan' and sending of the ctest results to the CDASH server
################################################################################

#-------------------------------------------------------------------------------
# Clang 7-11, C++98,11,14,17,20
#-------------------------------------------------------------------------------

# Clang 7, C++98, Release
linux_x86_64_clang7_cxx98_release_float_int:
  tags:
    - linux
  stage: test
  image: silkeh/clang:7
  script:
    - apt-get update -y
    - apt-get install cmake -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=98;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=float;-DGISMO_INDEX_TYPE=int;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan
    
# Clang 8, C++11, Release
linux_x86_64_clang8_cxx11_release_double_int32t:
  tags:
    - linux
  stage: test
  image: silkeh/clang:8
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=ON -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=11;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=double;-DGISMO_INDEX_TYPE=int32_t;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan

# Clang 9, C++14, Release
linux_x86_64_clang9_cxx14_release_longdouble_int64t:
  tags:
    - linux
  stage: test
  image: silkeh/clang:9
  script:
    - apt-get update -y
    - apt-get install cmake -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=14;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=long double;-DGISMO_INDEX_TYPE=int64_t;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan

# Clang 10, C++17, Release
linux_x86_64_clang10_cxx17_release_mpreal_long:
  tags:
    - linux
  stage: test
  image: silkeh/clang:10
  script:
    - apt-get update -y
    - apt-get install cmake libmpfr-dev ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=17;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpfr::mpreal;-DGISMO_INDEX_TYPE=long;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan

# Clang 11, C++20, Release
linux_x86_64_clang11_cxx20_release_mpq_longlong:
  tags:
    - linux
  stage: test
  image: silkeh/clang:11
  script:
    - apt-get update -y
    - apt-get install cmake libgmp-dev -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CNAME=/usr/local/bin/clang -D CXXNAME=/usr/local/bin/clang++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=20;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpq_class;-DGISMO_INDEX_TYPE=long long;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan


#-------------------------------------------------------------------------------
# GCC 6-10, C++98,11,14,17,20
#-------------------------------------------------------------------------------

# GCC 6, C++98, Release
linux_x86_64_gcc6_cxx98_release_mpq_longlong:
  tags:
    - linux
  stage: test
  image: gcc:6
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build libgmp-dev -y
    - apt-get install cmake libmpfr-dev -y #should not be needed but there is a bug in CMakeLists.txt when using ninja
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/gcc -D CXXNAME=/usr/local/bin/g++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=98;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpq_class;-DGISMO_INDEX_TYPE=long long;-DGISMO_WITH_ONURBS=ON' -Q #-VV
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan
    
# GCC 7, C++11, Release
linux_x86_64_gcc7_cxx11_release_mpreal_long:
  tags:
    - linux
  stage: test
  image: gcc:7
  script:
    - apt-get update -y
    - apt-get install cmake libmpfr-dev -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CNAME=/usr/local/bin/gcc -D CXXNAME=/usr/local/bin/g++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=11;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=mpfr::mpreal;-DGISMO_INDEX_TYPE=long;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan

# GCC 8, C++14, Release
linux_x86_64_gcc8_cxx14_release_longdouble_int64t:
  tags:
    - linux
  stage: test
  image: gcc:8
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/gcc -D CXXNAME=/usr/local/bin/g++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=14;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=long double;-DGISMO_INDEX_TYPE=int64_t;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan
    
# GCC 9, C++17, Release
linux_x86_64_gcc9_cxx17_release_double_int32t:
  
  tags:
    - linux
  stage: test
  image: gcc:9
  script:
    - apt-get update -y
    - apt-get install cmake -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CNAME=/usr/local/bin/gcc -D CXXNAME=/usr/local/bin/g++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=17;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=double;-DGISMO_INDEX_TYPE=int32_t;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan

# GCC 10, C++20, Release
linux_x86_64_gcc10_cxx20_release_float_int:
  tags:
    - linux
  stage: test
  image: gcc:10
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S /builds/gismo-ci/gismo/cmake/ctest_script.cmake -D CTEST_BUILD_NAME="$CI_JOB_NAME" -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_SOURCE_DIRECTORY=/builds/gismo-ci/gismo -D CTEST_CONFIGURATION_TYPE=Release -D UPDATE_REPO=OFF -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=/usr/local/bin/gcc -D CXXNAME=/usr/local/bin/g++ -D CTEST_TEST_TIMEOUT=150 -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=20;-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_COEFF_TYPE=float;-DGISMO_INDEX_TYPE=int;-DGISMO_WITH_ONURBS=ON' -Q
  except:
    - external_pull_requests
    - ci_test
    - coverity_scan
    
################################################################################
# 2. Building and testing of external pull requests (PRs)
################################################################################

################################################################################
# 3. Building and extensive testing of commits to branch 'ci_test'
################################################################################

################################################################################
# 4. Coverity scan of commits to branch 'coverity_scan'
################################################################################
