stages:
  - build

# GCC 8, C++98, Release
linux_gcc8_cxx98_release:
  tags:
    - linux
  stage: build
  image: gcc:8
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S cmake/ctest_script.cmake -D CTEST_CONFIGURATION_TYPE=Release -D CTEST_BUILD_JOBS=4 -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=gcc -D CXXNAME=g++ -D CTEST_TEST_TIMEOUT=150 -D DO_COVERAGE=ON -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=98' -Q
  except:
    - external_pull_requests
    
# GCC 9, C++11, Release
linux_gcc9_cxx11_release:
  tags:
    - linux
  stage: build
  image: gcc:9
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S cmake/ctest_script.cmake -D CTEST_CONFIGURATION_TYPE=Release -D CTEST_BUILD_JOBS=4 -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=gcc -D CXXNAME=g++ -D CTEST_TEST_TIMEOUT=150 -D DO_COVERAGE=ON -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=11' -Q
  except:
    - external_pull_requests

# GCC 10, C++14, Release
linux_gcc10_cxx14_release:
  tags:
    - linux
  stage: build
  image: gcc:10
  script:
    - apt-get update -y
    - apt-get install cmake ninja-build -y
    - ctest -S cmake/ctest_script.cmake -D CTEST_CONFIGURATION_TYPE=Release -D CTEST_BUILD_JOBS=4 -D CTEST_CMAKE_GENERATOR=Ninja -D CNAME=gcc -D CXXNAME=g++ -D CTEST_TEST_TIMEOUT=150 -D DO_COVERAGE=ON -D GISMO_SUBMODULES='' -D LABELS_FOR_SUBPROJECTS='gismo;examples;unittests;doc-snippets' -D CMAKE_ARGS='-DCMAKE_CXX_STANDARD=14' -Q
  except:
    - external_pull_requests
