stages:
  - build

# GCC 8, C++98, Release
linux_gcc8_cxx98_release:
  tags:
    - linux
  stage: build
  image: gcc:8
  script:
    - apt-get update -y
    - apt-get install cmake -y
    - mkdir -p build
    - cd build
    - CC=gcc CXX=g++  cmake .. -DCMAKE_CXX_STANDARD=98 -DCMAKE_BUILD_TYPE=Release
    - make -j4
    - make test
  except:
    - external_pull_requests

#always-run:
#  script: echo 'this should always run update'

#on-pull-requests:
#  script: echo 'this should run on pull requests'
#  only:
#    - external_pull_requests

#except-pull-requests:
#  script: echo 'this should not run on pull requests'
#  except:
#    - external_pull_requests
