################################################################################
# GitLab CI is used for multiple purposes
#
# 1. Building and testing of commits to all branches except 'ci_test' and 
#   'coverity_scan' and sending of the ctest results to the CDASH server
#    - these jobs exclude external pull requests and the two branches 
#      'ci_test' and 'coverity_scan' by the rule
#       except:
#       - external_pull_requests
#       - ci_test
#       - coverity_scan
#
# 2. Building and testing of external pull requests (PRs) [to be added]
#
# 3. Building and extensive testing of commits to branch 'ci_test' [to be added]
#
# 4. Coverity scan of commits to branch 'coverity_scan' [to be added]
################################################################################

stages:
  - test

################################################################################
# 5. Test installation and deployment
################################################################################

# Standard installation and deployment on linux
install_and_deploy_linux:
  tags:
    - linux
  stage: test
  image: gcc:9
  script:
    - apt-get update -y
    - apt-get install cmake -y
    - export MAKEFLAGS=-j3
    - mkdir /builds/gismo-ci/buildlib; cd /builds/gismo-ci/buildlib
    - cmake ../gismo -DBUILDNAME="$CI_JOB_NAME" -DSITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles" #-DGISMO_BUILD_UNITTESTS=ON -DGISMO_WITH_ONURBS=ON -DGISMO_WITH_GMP=ON -DGISMO_WITH_MPFR=ON -DGISMO_WITH_IPOPT=ON -DGISMO_WITH_SPECTRA=ON -DGISMO_WITH_SUPERLU=ON -DGISMO_WITH_UMFPACK=ON
    - cmake --build . --target gismo #--parallel 3
    # I. Test deploy from build tree
    - cp /builds/gismo-ci/gismo/CTestConfig.cmake /builds/gismo-ci/gismo/deploy/
    - mv /builds/gismo-ci/gismo/examples/*.cpp /builds/gismo-ci/gismo/deploy/
    - mkdir /builds/gismo-ci/build; cd /builds/gismo-ci/build
    - cmake ../gismo/deploy -Dgismo_DIR=/builds/gismo-ci/buildlib -DBUILDNAME="$CI_JOB_NAME-local" -DSITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles"
    - ctest $MAKEFLAGS --output-on-failure -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit
    # II. Test deploy from system tree
    - cmake --build . --target install
    - rm -rf ~/.cmake /builds/gismo-ci/buildlib /builds/gismo-ci/build
    - mkdir /builds/gismo-ci/build; cd /builds/gismo-ci/build
    - cp /builds/gismo-ci/gismo/CTestConfig.cmake /builds/gismo-ci/gismo/deploy/
    - cmake ../gismo -DBUILDNAME="$CI_JOB_NAME-system" -DSITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [gitlab-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles"
    - ctest $MAKEFLAGS --output-on-failure -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit
  only:
    - install_test
