version: 2.0

jobs:
  macos_x86_64_xcode11_cxx98_release:
    macos:
      xcode: "11.7.0"
    filters:
      branches:
        - only: stable
    working_directory: ~/gismo
    environment:
      MAKEFLAGS: -j4
    steps:
      - run:
          name: Install dependencies
          command: brew install cmake
      - checkout
      - run:
          name: Configure G+Smo on MacOS
          command: cmake . -DSITE="$CIRCLE_USERNAME-$CIRCLE_BRANCH [macos_x86_64_xcode11_cxx98_release]" -DGISMO_INSOURCE_BUILD=ON -DGISMO_BUILD_UNITTESTS=ON -DCMAKE_CXX_STANDARD=98 -DGISMO_WITH_ONURBS=ON
      - run:
          name: Build and test G+Smo on MacOS
          command: ctest $MAKEFLAGS --output-on-failure -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit #-D ExperimentalMemCheck

  macos_x86_64_xcode12_cxx11_release:
    macos:
      xcode: "12.1.0"
    filters:
      branches:
        - only: stable
    working_directory: ~/gismo
    environment:
      MAKEFLAGS: -j4
    steps:
      - run:
          name: Install dependencies
          command: brew install cmake
      - checkout
      - run:
          name: Configure G+Smo on MacOS
          command: cmake . -DSITE="$CIRCLE_USERNAME-$CIRCLE_BRANCH [macos_x86_64_xcode12_cxx11_release]" -DGISMO_INSOURCE_BUILD=ON -DGISMO_BUILD_UNITTESTS=ON -DCMAKE_CXX_STANDARD=11 -DGISMO_WITH_ONURBS=ON
      - run:
          name: Build and test G+Smo on MacOS
          command: ctest $MAKEFLAGS --output-on-failure -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit #-D ExperimentalMemCheck

workflows:
  version: 2
  build:
    jobs:
      - macos_x86_64_xcode11_cxx98_release
      - macos_x86_64_xcode12_cxx11_release
